name: Nix CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  shared:
    uses: wyatt-avilla/nix-ci/.github/workflows/nix-ci.yml@main
    with:
      use_secret: true
    secrets:
      CI_DEPLOY_KEY: ${{ secrets.CI_DEPLOY_KEY }}
